# 178. Rank Scores

Table: Scores+-------------+---------+| Column Name | Type    |+-------------+---------+| id          | int     || score       | decimal |+-------------+---------+id is the primary key (column with unique values) for this table.Each row of this table contains the score of a game. Score is a floating point value with two decimal places. Write a solution to find the rank of the scores. The ranking should be calculated according to the following rules:The scores should be ranked from the highest to the lowest.If there is a tie between two scores, both should have the same ranking.After a tie, the next ranking number should be the next consecutive integer value. In other words, there should be no holes between ranks.Return the result table ordered by score in descending order.The result format is in the following example. **Example 1:**Input: Scores table:+----+-------+| id | score |+----+-------+| 1  | 3.50  || 2  | 3.65  || 3  | 4.00  || 4  | 3.85  || 5  | 4.00  || 6  | 3.65  |+----+-------+Output: +-------+------+| score | rank |+-------+------+| 4.00  | 1    || 4.00  | 1    || 3.85  | 2    || 3.65  | 3    || 3.65  | 3    || 3.50  | 4    |+-------+------+

## Solution Explanation
This problem asks us to rank scores from highest to lowest, with tied scores receiving the same rank, and no gaps in the ranking.The key insight is to use the `DENSE_RANK()` window function in SQL. This function assigns a rank to each distinct value within a result set, with no gaps in the ranking values. This is exactly what we need for this problem.The `DENSE_RANK()` function differs from the regular `RANK()` function in that it doesn't leave gaps in the ranking when there are ties. For example, if two records tie for first place, both get a rank of 1, and the next record gets a rank of 2 (not 3, which would happen with `RANK()`).We'll order the scores in descending order as required, and then apply the `DENSE_RANK()` function to assign ranks.

In [ ]:
sqlSELECT     score,    DENSE_RANK() OVER (ORDER BY score DESC) as 'rank'FROM     ScoresORDER BY     score DESC;

## Time and Space Complexity
* *Time Complexity**: O(n log n), where n is the number of rows in the Scores table. This is because the database needs to sort the scores to apply the ranking, which typically takes O(n log n) time.* *Space Complexity**: O(n) for storing the result set, which includes all scores and their corresponding ranks.

## Test Cases

In [ ]:
Since this is a SQL problem, I'll provide test cases in the form of SQL statements to create and populate a test table, and then run our solution on it:sql-- Test Case 1: Basic case with tiesCREATE TABLE Scores (    id INT PRIMARY KEY,    score DECIMAL(3,2));INSERT INTO Scores (id, score) VALUES(1, 3.50),(2, 3.65),(3, 4.00),(4, 3.85),(5, 4.00),(6, 3.65);-- Run our solutionSELECT     score,    DENSE_RANK() OVER (ORDER BY score DESC) as 'rank'FROM     ScoresORDER BY     score DESC;-- Expected output:-- +-------+------+-- | score | rank |-- +-------+------+-- | 4.00  | 1    |-- | 4.00  | 1    |-- | 3.85  | 2    |-- | 3.65  | 3    |-- | 3.65  | 3    |-- | 3.50  | 4    |-- +-------+------+-- Test Case 2: All scores are the sameDELETE FROM Scores;INSERT INTO Scores (id, score) VALUES(1, 3.50),(2, 3.50),(3, 3.50);-- Run our solutionSELECT     score,    DENSE_RANK() OVER (ORDER BY score DESC) as 'rank'FROM     ScoresORDER BY     score DESC;-- Expected output:-- +-------+------+-- | score | rank |-- +-------+------+-- | 3.50  | 1    |-- | 3.50  | 1    |-- | 3.50  | 1    |-- +-------+------+-- Test Case 3: All scores are differentDELETE FROM Scores;INSERT INTO Scores (id, score) VALUES(1, 3.50),(2, 3.65),(3, 4.00);-- Run our solutionSELECT     score,    DENSE_RANK() OVER (ORDER BY score DESC) as 'rank'FROM     ScoresORDER BY     score DESC;-- Expected output:-- +-------+------+-- | score | rank |-- +-------+------+-- | 4.00  | 1    |-- | 3.65  | 2    |-- | 3.50  | 3    |-- +-------+------+